{
  "openapi": "3.0.0",
  "x-stoplight": {
    "id": "h39bgcco5oxcm"
  },
  "info": {
    "title": "academic-information",
    "version": "1.0"
  },
  "servers": [
    {
      "url": "http://localhost:3000"
    }
  ],
  "paths": {
    "/users/{userId}": {
      "parameters": [
        {
          "schema": {
            "type": "integer"
          },
          "name": "userId",
          "in": "path",
          "required": true,
          "description": "Id of an existing user."
        }
      ],
      "get": {
        "summary": "Get User Info by User ID",
        "tags": [],
        "responses": {
          "200": {
            "description": "User Found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/User"
                },
                "examples": {
                  "Get User Alice Smith": {
                    "value": {
                      "id": 142,
                      "firstName": "Alice",
                      "lastName": "Smith",
                      "email": "alice.smith@gmail.com",
                      "dateOfBirth": "1997-10-31",
                      "emailVerified": true,
                      "signUpDate": "2019-08-24"
                    }
                  }
                }
              }
            }
          },
          "404": {
            "description": "User Not Found"
          }
        },
        "operationId": "get-users-userId",
        "description": "Retrieve the information of the user with the matching user ID.",
        "x-stoplight": {
          "id": "30it0pd6aok4d"
        }
      },
      "patch": {
        "summary": "Update User Information",
        "operationId": "patch-users-userId",
        "responses": {
          "200": {
            "description": "User Updated",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/User"
                },
                "examples": {
                  "Updated User Rebecca Baker": {
                    "value": {
                      "id": 13,
                      "firstName": "Rebecca",
                      "lastName": "Baker",
                      "email": "rebecca@gmail.com",
                      "dateOfBirth": "1985-10-02",
                      "emailVerified": false,
                      "createDate": "2019-08-24"
                    }
                  }
                }
              }
            }
          },
          "404": {
            "description": "User Not Found"
          },
          "409": {
            "description": "Email Already Taken"
          }
        },
        "description": "Update the information of an existing user.",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "firstName": {
                    "type": "string"
                  },
                  "lastName": {
                    "type": "string"
                  },
                  "email": {
                    "type": "string",
                    "description": "If a new email is given, the user's email verified property will be set to false."
                  },
                  "dateOfBirth": {
                    "type": "string"
                  }
                }
              },
              "examples": {
                "Update First Name": {
                  "value": {
                    "firstName": "Rebecca"
                  }
                },
                "Update Email": {
                  "value": {
                    "email": "rebecca@gmail.com"
                  }
                },
                "Update Last Name & Date of Birth": {
                  "value": {
                    "lastName": "Baker",
                    "dateOfBirth": "1985-10-02"
                  }
                }
              }
            }
          },
          "description": "Patch user properties to update."
        },
        "x-stoplight": {
          "id": "ldosmoicnhsgf"
        }
      }
    },
    "/user": {
      "post": {
        "summary": "Create New User",
        "operationId": "post-user",
        "responses": {
          "200": {
            "description": "User Created",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/User"
                },
                "examples": {
                  "New User Bob Fellow": {
                    "value": {
                      "id": 12,
                      "firstName": "Bob",
                      "lastName": "Fellow",
                      "email": "bob.fellow@gmail.com",
                      "dateOfBirth": "1996-08-24",
                      "emailVerified": false,
                      "createDate": "2020-11-18"
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Missing Required Information"
          },
          "409": {
            "description": "Email Already Taken"
          }
        },
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "firstName": {
                    "type": "string"
                  },
                  "lastName": {
                    "type": "string"
                  },
                  "email": {
                    "type": "string"
                  },
                  "dateOfBirth": {
                    "type": "string",
                    "format": "date"
                  }
                },
                "required": [
                  "firstName",
                  "lastName",
                  "email",
                  "dateOfBirth"
                ]
              },
              "examples": {
                "Create User Bob Fellow": {
                  "value": {
                    "firstName": "Bob",
                    "lastName": "Fellow",
                    "email": "bob.fellow@gmail.com",
                    "dateOfBirth": "1996-08-24"
                  }
                }
              }
            }
          },
          "description": "Post the necessary fields for the API to create a new user."
        },
        "description": "Create a new user.",
        "x-stoplight": {
          "id": "8crwz9i3guut3"
        }
      }
    },
    "/1.0.0/academic/information/consent-requests/sections": {
      "get": {
        "summary": "Your GET endpoint",
        "tags": [],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/AcademicInformationConsentRequestGetResponse"
                }
              }
            }
          }
        },
        "operationId": "get-1.0.0-academic-information-consent-requests-sections",
        "x-stoplight": {
          "id": "f0xstxkde3uw8"
        },
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/AcademicInformationConsentRequestGetRequest"
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "AcademicInformationConsentRequestGetResponse": {
        "type": "object",
        "x-examples": {
          "Example 1": {
            "total": 27,
            "from": 1,
            "per_page": 10,
            "current_page": 1,
            "last_page": 3,
            "sections": [
              {
                "id": 47247,
                "course_code": "MAT 204",
                "course_title": "Mathematical analysis 4",
                "section": "01-N",
                "teacher": "Birzhan Ayanbayev",
                "pending_requests_count": 0,
                "accepted_requests_count": 0,
                "rejected_requests_count": 10
              },
              {
                "id": 47252,
                "course_code": "MAT 204",
                "course_title": "Mathematical analysis 4",
                "section": "03-N",
                "teacher": "Birzhan Ayanbayev",
                "pending_requests_count": 1,
                "accepted_requests_count": 0,
                "rejected_requests_count": 5
              },
              {
                "id": 47969,
                "course_code": "MAT 251",
                "course_title": "Probability and Mathematical Statictics",
                "section": "01-N",
                "teacher": "Larissa Bazarbayeva",
                "pending_requests_count": 2,
                "accepted_requests_count": 2,
                "rejected_requests_count": 3
              },
              {
                "id": 47460,
                "course_code": "MAT 371",
                "course_title": "Functional analysis",
                "section": "02-N",
                "teacher": "Nurlan Dairbekov",
                "pending_requests_count": 2,
                "accepted_requests_count": 7,
                "rejected_requests_count": 8
              },
              {
                "id": 48406,
                "course_code": "INF 371",
                "course_title": "Automation in Testing",
                "section": "01-N",
                "teacher": "Alisher Duzmagambetov",
                "pending_requests_count": 1,
                "accepted_requests_count": 8,
                "rejected_requests_count": 2
              },
              {
                "id": 50324,
                "course_code": "MAT 116",
                "course_title": "Mathematical analysis 2",
                "section": "10-N",
                "teacher": "Kuatkan Zhensikbayev",
                "pending_requests_count": 12,
                "accepted_requests_count": 0,
                "rejected_requests_count": 0
              },
              {
                "id": 47180,
                "course_code": "MAT 221",
                "course_title": "Classical mechanics",
                "section": "02-N",
                "teacher": "Nail Ussembayev",
                "pending_requests_count": 1,
                "accepted_requests_count": 1,
                "rejected_requests_count": 7
              },
              {
                "id": 47970,
                "course_code": "MAT 251",
                "course_title": "Probability and Mathematical Statictics",
                "section": "02-N",
                "teacher": "Larissa Bazarbayeva",
                "pending_requests_count": 1,
                "accepted_requests_count": 0,
                "rejected_requests_count": 1
              },
              {
                "id": 46394,
                "course_code": "MAT 364",
                "course_title": "Cryptography",
                "section": "01-N",
                "teacher": "Nargiza Tazabekova",
                "pending_requests_count": 0,
                "accepted_requests_count": 8,
                "rejected_requests_count": 14
              },
              {
                "id": 47171,
                "course_code": "MAT 116",
                "course_title": "Mathematical analysis 2",
                "section": "02-N",
                "teacher": "Mukhtar Ismagulov",
                "pending_requests_count": 8,
                "accepted_requests_count": 0,
                "rejected_requests_count": 0
              }
            ]
          }
        },
        "properties": {
          "total": {
            "type": "integer"
          },
          "from": {
            "type": "integer"
          },
          "per_page": {
            "type": "integer"
          },
          "current_page": {
            "type": "integer"
          },
          "last_page": {
            "type": "integer"
          },
          "sections": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "id": {
                  "type": "integer"
                },
                "course_code": {
                  "type": "string"
                },
                "course_title": {
                  "type": "string"
                },
                "section": {
                  "type": "string"
                },
                "teacher": {
                  "type": "string"
                },
                "pending_requests_count": {
                  "type": "integer"
                },
                "accepted_requests_count": {
                  "type": "integer"
                },
                "rejected_requests_count": {
                  "type": "integer"
                }
              },
              "required": [
                "id",
                "course_code",
                "course_title",
                "section",
                "teacher",
                "pending_requests_count",
                "accepted_requests_count",
                "rejected_requests_count"
              ]
            }
          }
        },
        "required": [
          "total",
          "from",
          "per_page",
          "current_page",
          "last_page",
          "sections"
        ]
      },
      "AcademicInformationConsentRequestGetRequest": {
        "type": "object",
        "x-examples": {
          "Example 1": {
            "year": 12412,
            "term": 124,
            "offset": 12,
            "per_page": 12
          }
        },
        "properties": {
          "year": {
            "type": "integer"
          },
          "term": {
            "type": "integer"
          },
          "offset": {
            "type": "integer"
          },
          "per_page": {
            "type": "integer"
          }
        },
        "required": [
          "year",
          "term",
          "offset",
          "per_page"
        ]
      },
      "AcademicMyScheduleGetRequest": {
        "type": "object",
        "x-examples": {
          "Example 1": {
            "year": 2022,
            "term": 1,
            "course_code": "CSS 122"
          }
        },
        "properties": {
          "year": {
            "type": "integer"
          },
          "term": {
            "type": "integer"
          },
          "course_code": {
            "type": "string"
          }
        },
        "required": [
          "year",
          "term",
          "course_code"
        ]
      }
    }
  }
}